{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ipaddress
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ipaddress_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ipaddress/ipaddress_{{ version }}.tar.gz
  sha256: fccc6b03daa44db307102cd39f27961fdb670eefc9def657d70baf2558f61d37

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-asioheaders
    - r-rcpp
    - r-cli >=3.4.0
    - r-rlang >=1.0.3
    - r-vctrs
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-asioheaders
    - r-rcpp
    - r-cli >=3.4.0
    - r-rlang >=1.0.3
    - r-vctrs

test:
  commands:
    - $R -e "library('ipaddress')"           # [not win]
    - "\"%R%\" -e \"library('ipaddress')\""  # [win]

about:
  home: https://davidchall.github.io/ipaddress
  dev_url: https://github.com/davidchall/ipaddress
  license: MIT
  summary: Classes and functions for working with IP (Internet Protocol) addresses and networks, inspired by the Python 'ipaddress' module.  Offers full support for both IPv4 and IPv6 (Internet Protocol versions 4 and 6) address spaces. It is specifically designed to work well with the 'tidyverse'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
