{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ipaddress
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ipaddress_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ipaddress/ipaddress_{{ version }}.tar.gz
  sha256: 8dd8cd242a39e2b5e6f3349fa9fe64d5da3287df500e31cbcb5c0535814b3f4f

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-asioheaders
    - r-bh
    - r-rcpp
    - r-blob >=1.2.0
    - r-rlang >=0.4.0
    - r-vctrs >=0.3.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-asioheaders
    - r-bh
    - r-rcpp
    - r-blob >=1.2.0
    - r-rlang >=0.4.0
    - r-vctrs >=0.3.0

test:
  commands:
    - $R -e "library('ipaddress')"           # [not win]
    - "\"%R%\" -e \"library('ipaddress')\""  # [win]

about:
  home: https://davidchall.github.io/ipaddress, https://github.com/davidchall/ipaddress
  license: MIT
  summary: Classes and functions for working with IP (Internet Protocol) addresses and networks, inspired by the Python 'ipaddress' module.  Offers full support for both IPv4 and IPv6 (Internet Protocol versions 4 and 6) address spaces. It is specifically designed to work well with the 'tidyverse'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc

# Package: ipaddress
# Title: Tidy IP Addresses
# Version: 0.2.0
# Authors@R: person(given = "David", family = "Hall", role = c("aut", "cre"), email = "david.hall.physics@gmail.com", comment = c(ORCID = "0000-0002-2193-0480"))
# Description: Classes and functions for working with IP (Internet Protocol) addresses and networks, inspired by the Python 'ipaddress' module.  Offers full support for both IPv4 and IPv6 (Internet Protocol versions 4 and 6) address spaces. It is specifically designed to work well with the 'tidyverse'.
# License: MIT + file LICENSE
# URL: https://davidchall.github.io/ipaddress, https://github.com/davidchall/ipaddress
# BugReports: https://github.com/davidchall/ipaddress/issues
# Depends: R (>= 3.2.0)
# Imports: blob (>= 1.2.0), methods, Rcpp, rlang (>= 0.4.0), vctrs (>= 0.2.2)
# Suggests: knitr, rmarkdown, testthat (>= 2.1.0)
# LinkingTo: AsioHeaders, Rcpp
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.0
# SystemRequirements: C++11
# NeedsCompilation: yes
# Packaged: 2020-03-25 17:06:17 UTC; david
# Author: David Hall [aut, cre] (<https://orcid.org/0000-0002-2193-0480>)
# Maintainer: David Hall <david.hall.physics@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-03-25 17:30:02 UTC
